### ISSUE TITLE
Failed to create NativeModule "UIManager"

### ISSUE THREAD

**Issue by ismael-miber-elcoach** [react-native-community/react-native-video#3051]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
 System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 18.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /var/folders/ck/g3src5dd27q9g67pgfk2swt80000gn/T/yarn--1678124872777-0.9732115222260669/node
    Yarn: 1.22.19 - /var/folders/ck/g3src5dd27q9g67pgfk2swt80000gn/T/yarn--1678124872777-0.9732115222260669/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 2023.01.16.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 27, 28, 29, 31, 33
      Build Tools: 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 34.0.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.68.6 => 0.68.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.1

## Steps To Reproduce

1. yarn android OR run from Android Studio
2. The app open and load bundle
3. The app crashed
4. the error that appear in Android Studio is:
```bash
Failed to create NativeModule "UIManager"
	java.lang.VerifyError: Verifier rejected class com.brentvatne.exoplayer.ReactExoplayerViewManager: android.view.View com.brentvatne.exoplayer.ReactExoplayerViewManager.createViewInstance(com.facebook.react.uimanager.ThemedReactContext) failed to verify: android.view.View com.brentvatne.exoplayer.ReactExoplayerViewManager.createViewInstance(com.facebook.react.uimanager.ThemedReactContext): [0x4]  can't resolve returned type 'Reference: android.view.View' or 'Unresolved Reference: com.brentvatne.exoplayer.ReactExoplayerView' (declaration of 'com.brentvatne.exoplayer.ReactExoplayerViewManager' appears in /data/app/~~V83nqDsgB0_P80mbNOvHKg==/com.elcoach.me-JEtRARns8k24Oz97SFw9RA==/base.apk!classes9.dex)
	at com.brentvatne.react.ReactVideoPackage.createViewManagers(ReactVideoPackage.java:42)
	at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:932)
	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:197)
	at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:162)
	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159)
	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147)
	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:172)
	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:502)
	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:478)
	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:89)
	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:47)
	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1241)
	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1186)
	at com.facebook.react.ReactInstanceManager.access$1600(ReactInstanceManager.java:138)
	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1139)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:920)
	2023-03-06 19:47:02.668 19856-20149 AndroidRuntime          com.elcoach.me                       E  FATAL EXCEPTION: mqt_native_modules
	Process: com.elcoach.me, PID: 19856
	java.lang.VerifyError: Verifier rejected class com.brentvatne.exoplayer.ReactExoplayerViewManager: android.view.View com.brentvatne.exoplayer.ReactExoplayerViewManager.createViewInstance(com.facebook.react.uimanager.ThemedReactContext) failed to verify: android.view.View com.brentvatne.exoplayer.ReactExoplayerViewManager.createViewInstance(com.facebook.react.uimanager.ThemedReactContext): [0x4]  can't resolve returned type 'Reference: android.view.View' or 'Unresolved Reference: com.brentvatne.exoplayer.ReactExoplayerView' (declaration of 'com.brentvatne.exoplayer.ReactExoplayerViewManager' appears in /data/app/~~V83nqDsgB0_P80mbNOvHKg==/com.elcoach.me-JEtRARns8k24Oz97SFw9RA==/base.apk!classes9.dex)
	at com.brentvatne.react.ReactVideoPackage.createViewManagers(ReactVideoPackage.java:42)
	at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:932)
	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:197)
	at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:162)
	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:159)
	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:147)
	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:172)
	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:502)
	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:478)
	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:89)
	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:47)
at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1241)
at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1186)
at com.facebook.react.ReactInstanceManager.access$1600(ReactInstanceManager.java:138)
at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1139)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
at java.lang.Thread.run(Thread.java:920)
```

## Expected behaviour

1. run without crashing.

No changes happened in our project, it was working perfectly and suddenly this happen, I tried also the test project of react-native-video with the version that I use in my project and it works without crashing.

Can anyone help there, I tried a lot of things but didn't get a solution for this issue.

**Comment by ismael-miber-elcoach** [comment]
Finally, We in our company found the issue, the package got the exoplayer latest version and that makes this issue, to fix it you must force the version of exoplayer that used by `react-native-video` by going to `build.gradle` and put this code:

```
allprojects {
    configurations.all {
        resolutionStrategy { 
            force 'com.google.android.exoplayer:exoplayer:2.13.3'
        }
    }
}
```

**Comment by ismael-miber-elcoach** [comment]
I will close it as it is fixed.

**Comment by gmferraz** [comment]
Amazing job @ismael-miber-elcoach. Life safer, was trying to find a solution since Friday

**Comment by Manhha3010** [comment]
> Finally, We in our company found the issue, the package got the exoplayer latest version and that makes this issue, to fix it you must force the version of exoplayer that used by `react-native-video` by going to `build.gradle` and put this code:
> 
> ```
> allprojects {
>     configurations.all {
>         resolutionStrategy { 
>             force 'com.google.android.exoplayer:exoplayer:2.13.3'
>         }
>     }
> }
> ```

Greate
